CPPFLAGS=-std=c++11 -O2

all::blowing_candles_scanf blowing_candles Main.class

blowing_candles_scanf: blowing_candles_scanf.cpp

blowing_candles: blowing_candles.cpp

Main.class: BlowingCandles.java
	javac BlowingCandles.java

